// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDr6nqFLU40ENXQb9QLKY8y_dYn2alh0',
    appId: '1:801150249120:web:85da759862e2716e9781c5',
    messagingSenderId: '801150249120',
    projectId: 'foodapp-bf10d',
    authDomain: 'foodapp-bf10d.firebaseapp.com',
    storageBucket: 'foodapp-bf10d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDx9jxn6qdvZQBIjvgwad_oKual2fjWw0',
    appId: '1:801150249120:android:c1a2e99702dae3869781c5',
    messagingSenderId: '801150249120',
    projectId: 'foodapp-bf10d',
    storageBucket: 'foodapp-bf10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkFLy_GgEzsAfWYsxc05DuHJ0Gx8-YKNI',
    appId: '1:801150249120:ios:c2c22e3380a732bd9781c5',
    messagingSenderId: '801150249120',
    projectId: 'foodapp-bf10d',
    storageBucket: 'foodapp-bf10d.appspot.com',
    iosClientId: '801150249120-2boauol28s8qfd95l45ofamv5ejktqf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.foodapp',
  );
}
